[2022-10-04T11:40:30.016+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag_with_minio_s3_v1.sensor_minio_s3 scheduled__2022-10-02T00:00:00+00:00 [queued]>
[2022-10-04T11:40:30.046+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag_with_minio_s3_v1.sensor_minio_s3 scheduled__2022-10-02T00:00:00+00:00 [queued]>
[2022-10-04T11:40:30.047+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-10-04T11:40:30.053+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 3
[2022-10-04T11:40:30.053+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-10-04T11:40:30.085+0000] {taskinstance.py:1383} INFO - Executing <Task(S3KeySensor): sensor_minio_s3> on 2022-10-02 00:00:00+00:00
[2022-10-04T11:40:30.092+0000] {standard_task_runner.py:54} INFO - Started process 9823 to run task
[2022-10-04T11:40:30.098+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_with_minio_s3_v1', 'sensor_minio_s3', 'scheduled__2022-10-02T00:00:00+00:00', '--job-id', '95', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_minio_s3.py', '--cfg-path', '/tmp/tmp_hjuoobm']
[2022-10-04T11:40:30.101+0000] {standard_task_runner.py:83} INFO - Job 95: Subtask sensor_minio_s3
[2022-10-04T11:40:30.103+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/dag_with_minio_s3.py
[2022-10-04T11:40:30.678+0000] {task_command.py:384} INFO - Running <TaskInstance: dag_with_minio_s3_v1.sensor_minio_s3 scheduled__2022-10-02T00:00:00+00:00 [running]> on host fe59f3828ca7
[2022-10-04T11:40:30.792+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dag_with_minio_s3_v1
AIRFLOW_CTX_TASK_ID=sensor_minio_s3
AIRFLOW_CTX_EXECUTION_DATE=2022-10-02T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-02T00:00:00+00:00
[2022-10-04T11:40:30.793+0000] {s3.py:98} INFO - Poking for key : s3://***/data.csv
[2022-10-04T11:40:30.809+0000] {base.py:71} INFO - Using connection ID 'minio_conn' for task execution.
[2022-10-04T11:40:30.811+0000] {connection_wrapper.py:303} INFO - AWS Connection (conn_id='minio_conn', conn_type='aws') credentials retrieved from login and password.
[2022-10-04T11:40:30.823+0000] {logging_mixin.py:117} WARNING - /home/***/.local/lib/python3.7/site-packages/***/providers/amazon/aws/utils/connection_wrapper.py:8 DeprecationWarning: extra['host'] is deprecated and will be removed in a future release. Please set extra['endpoint_url'] instead
[2022-10-04T11:40:30.966+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 189, in execute
    poke_return = self.poke(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/sensors/s3.py", line 128, in poke
    return all(self._check_key(key) for key in self.bucket_key)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/sensors/s3.py", line 128, in <genexpr>
    return all(self._check_key(key) for key in self.bucket_key)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/sensors/s3.py", line 117, in _check_key
    obj = self.get_hook().head_object(key, bucket_name)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 64, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 92, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 466, in head_object
    raise e
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 461, in head_object
    return self.get_conn().head_object(Bucket=bucket_name, Key=key)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 514, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 938, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (400) when calling the HeadObject operation: Bad Request
[2022-10-04T11:40:30.978+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_minio_s3_v1, task_id=sensor_minio_s3, execution_date=20221002T000000, start_date=20221004T114030, end_date=20221004T114030
[2022-10-04T11:40:30.999+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 95 for task sensor_minio_s3 (An error occurred (400) when calling the HeadObject operation: Bad Request; 9823)
[2022-10-04T11:40:31.033+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-10-04T11:40:31.078+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
