[2022-10-04T12:18:12.529+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_hooks_v1.postgres_to_s3 manual__2022-10-04T12:18:10.387022+00:00 [queued]>
[2022-10-04T12:18:12.555+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_hooks_v1.postgres_to_s3 manual__2022-10-04T12:18:10.387022+00:00 [queued]>
[2022-10-04T12:18:12.555+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-10-04T12:18:12.556+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 3
[2022-10-04T12:18:12.556+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-10-04T12:18:12.595+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): postgres_to_s3> on 2022-10-04 12:18:10.387022+00:00
[2022-10-04T12:18:12.604+0000] {standard_task_runner.py:54} INFO - Started process 14634 to run task
[2022-10-04T12:18:12.613+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_hooks_v1', 'postgres_to_s3', 'manual__2022-10-04T12:18:10.387022+00:00', '--job-id', '108', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_hooks.py', '--cfg-path', '/tmp/tmpe64t74o_']
[2022-10-04T12:18:12.616+0000] {standard_task_runner.py:83} INFO - Job 108: Subtask postgres_to_s3
[2022-10-04T12:18:12.619+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/dag_with_postgres_hooks.py
[2022-10-04T12:18:13.123+0000] {task_command.py:384} INFO - Running <TaskInstance: dag_with_postgres_hooks_v1.postgres_to_s3 manual__2022-10-04T12:18:10.387022+00:00 [running]> on host fe59f3828ca7
[2022-10-04T12:18:13.310+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dag_with_postgres_hooks_v1
AIRFLOW_CTX_TASK_ID=postgres_to_s3
AIRFLOW_CTX_EXECUTION_DATE=2022-10-04T12:18:10.387022+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-04T12:18:10.387022+00:00
[2022-10-04T12:18:13.335+0000] {base.py:71} INFO - Using connection ID 'postgres_localhost' for task execution.
[2022-10-04T12:18:13.379+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_with_postgres_hooks.py", line 19, in postgres_to_s3
    cursor.execute("select * from orders where data <= '20220501'")
psycopg2.errors.UndefinedColumn: column "data" does not exist
LINE 1: select * from orders where data <= '20220501'
                                   ^
HINT:  Perhaps you meant to reference the column "orders.date".

[2022-10-04T12:18:13.405+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_postgres_hooks_v1, task_id=postgres_to_s3, execution_date=20221004T121810, start_date=20221004T121812, end_date=20221004T121813
[2022-10-04T12:18:13.437+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 108 for task postgres_to_s3 (column "data" does not exist
LINE 1: select * from orders where data <= '20220501'
                                   ^
HINT:  Perhaps you meant to reference the column "orders.date".
; 14634)
[2022-10-04T12:18:13.469+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-10-04T12:18:13.522+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
