[2022-10-04T12:51:32.760+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_hooks_v2.postgres_to_s3 manual__2022-10-04T12:46:27.866080+00:00 [queued]>
[2022-10-04T12:51:32.789+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_hooks_v2.postgres_to_s3 manual__2022-10-04T12:46:27.866080+00:00 [queued]>
[2022-10-04T12:51:32.790+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-10-04T12:51:32.790+0000] {taskinstance.py:1363} INFO - Starting attempt 2 of 3
[2022-10-04T12:51:32.791+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-10-04T12:51:32.842+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): postgres_to_s3> on 2022-10-04 12:46:27.866080+00:00
[2022-10-04T12:51:32.852+0000] {standard_task_runner.py:54} INFO - Started process 19176 to run task
[2022-10-04T12:51:32.863+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_hooks_v2', 'postgres_to_s3', 'manual__2022-10-04T12:46:27.866080+00:00', '--job-id', '126', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_hooks.py', '--cfg-path', '/tmp/tmplkd0meu7']
[2022-10-04T12:51:32.870+0000] {standard_task_runner.py:83} INFO - Job 126: Subtask postgres_to_s3
[2022-10-04T12:51:32.875+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/dag_with_postgres_hooks.py
[2022-10-04T12:51:33.547+0000] {task_command.py:384} INFO - Running <TaskInstance: dag_with_postgres_hooks_v2.postgres_to_s3 manual__2022-10-04T12:46:27.866080+00:00 [running]> on host fe59f3828ca7
[2022-10-04T12:51:33.719+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dag_with_postgres_hooks_v2
AIRFLOW_CTX_TASK_ID=postgres_to_s3
AIRFLOW_CTX_EXECUTION_DATE=2022-10-04T12:46:27.866080+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-04T12:46:27.866080+00:00
[2022-10-04T12:51:33.732+0000] {logging_mixin.py:117} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:204 AirflowContextDeprecationWarning: Accessing 'next_ds_nodash' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds_nodash }}' instead.
[2022-10-04T12:51:33.752+0000] {base.py:71} INFO - Using connection ID 'postgres_localhost' for task execution.
[2022-10-04T12:51:33.789+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_with_postgres_hooks.py", line 30, in postgres_to_s3
    f.f
  File "/usr/local/lib/python3.7/tempfile.py", line 476, in __getattr__
    a = getattr(file, name)
AttributeError: '_io.TextIOWrapper' object has no attribute 'f'
[2022-10-04T12:51:33.807+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_postgres_hooks_v2, task_id=postgres_to_s3, execution_date=20221004T124627, start_date=20221004T125132, end_date=20221004T125133
[2022-10-04T12:51:33.834+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 126 for task postgres_to_s3 ('_io.TextIOWrapper' object has no attribute 'f'; 19176)
[2022-10-04T12:51:33.886+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-10-04T12:51:33.940+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
