[2022-10-04T08:01:58.933+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_v1.create_table manual__2022-10-04T08:01:57.419903+00:00 [queued]>
[2022-10-04T08:01:58.949+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_v1.create_table manual__2022-10-04T08:01:57.419903+00:00 [queued]>
[2022-10-04T08:01:58.950+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-10-04T08:01:58.950+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 3
[2022-10-04T08:01:58.950+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-10-04T08:01:58.971+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): create_table> on 2022-10-04 08:01:57.419903+00:00
[2022-10-04T08:01:58.974+0000] {standard_task_runner.py:54} INFO - Started process 11130 to run task
[2022-10-04T08:01:58.978+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_v1', 'create_table', 'manual__2022-10-04T08:01:57.419903+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmp0k6n67ln']
[2022-10-04T08:01:58.980+0000] {standard_task_runner.py:83} INFO - Job 43: Subtask create_table
[2022-10-04T08:01:58.981+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/dag_with_postgres_operator.py
[2022-10-04T08:01:59.185+0000] {task_command.py:384} INFO - Running <TaskInstance: dag_with_postgres_v1.create_table manual__2022-10-04T08:01:57.419903+00:00 [running]> on host e877189be071
[2022-10-04T08:02:00.350+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dag_with_postgres_v1
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2022-10-04T08:01:57.419903+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-04T08:01:57.419903+00:00
[2022-10-04T08:02:00.374+0000] {base.py:71} INFO - Using connection ID 'postgres_localhost' for task execution.
[2022-10-04T08:02:00.591+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 94, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 288, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 115, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "host.docker.local" to address: Name or service not known

[2022-10-04T08:02:00.613+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_postgres_v1, task_id=create_table, execution_date=20221004T080157, start_date=20221004T080158, end_date=20221004T080200
[2022-10-04T08:02:00.648+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 43 for task create_table (could not translate host name "host.docker.local" to address: Name or service not known
; 11130)
[2022-10-04T08:02:00.680+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-10-04T08:02:00.733+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
